# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nevis/amsterdam/share/seligman/conda/grams/bin/cmake

# The command to remove a file.
RM = /nevis/amsterdam/share/seligman/conda/grams/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /nevis/milne/files/apellot/GRAMS/GramsSim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /nevis/milne/files/apellot/GRAMS/GramsSim-work

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/nevis/amsterdam/share/seligman/conda/grams/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nevis/amsterdam/share/seligman/conda/grams/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /nevis/milne/files/apellot/GRAMS/GramsSim-work/CMakeFiles /nevis/milne/files/apellot/GRAMS/GramsSim-work//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /nevis/milne/files/apellot/GRAMS/GramsSim-work/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /nevis/milne/files/apellot/GRAMS/GramsSim-work/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GramsSimProjectUtilities

# Build rule for target.
GramsSimProjectUtilities: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GramsSimProjectUtilities
.PHONY : GramsSimProjectUtilities

# fast build rule for target.
GramsSimProjectUtilities/fast:
	$(MAKE) $(MAKESILENT) -f util/CMakeFiles/GramsSimProjectUtilities.dir/build.make util/CMakeFiles/GramsSimProjectUtilities.dir/build
.PHONY : GramsSimProjectUtilities/fast

#=============================================================================
# Target rules for targets named Dictionary

# Build rule for target.
Dictionary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Dictionary
.PHONY : Dictionary

# fast build rule for target.
Dictionary/fast:
	$(MAKE) $(MAKESILENT) -f GramsDataObj/CMakeFiles/Dictionary.dir/build.make GramsDataObj/CMakeFiles/Dictionary.dir/build
.PHONY : Dictionary/fast

#=============================================================================
# Target rules for targets named gramssky

# Build rule for target.
gramssky: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gramssky
.PHONY : gramssky

# fast build rule for target.
gramssky/fast:
	$(MAKE) $(MAKESILENT) -f GramsSky/CMakeFiles/gramssky.dir/build.make GramsSky/CMakeFiles/gramssky.dir/build
.PHONY : gramssky/fast

#=============================================================================
# Target rules for targets named gramsg4

# Build rule for target.
gramsg4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gramsg4
.PHONY : gramsg4

# fast build rule for target.
gramsg4/fast:
	$(MAKE) $(MAKESILENT) -f GramsG4/CMakeFiles/gramsg4.dir/build.make GramsG4/CMakeFiles/gramsg4.dir/build
.PHONY : gramsg4/fast

#=============================================================================
# Target rules for targets named gramsdetsim

# Build rule for target.
gramsdetsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gramsdetsim
.PHONY : gramsdetsim

# fast build rule for target.
gramsdetsim/fast:
	$(MAKE) $(MAKESILENT) -f GramsDetSim/CMakeFiles/gramsdetsim.dir/build.make GramsDetSim/CMakeFiles/gramsdetsim.dir/build
.PHONY : gramsdetsim/fast

#=============================================================================
# Target rules for targets named gramsreadoutsim

# Build rule for target.
gramsreadoutsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gramsreadoutsim
.PHONY : gramsreadoutsim

# fast build rule for target.
gramsreadoutsim/fast:
	$(MAKE) $(MAKESILENT) -f GramsReadoutSim/CMakeFiles/gramsreadoutsim.dir/build.make GramsReadoutSim/CMakeFiles/gramsreadoutsim.dir/build
.PHONY : gramsreadoutsim/fast

#=============================================================================
# Target rules for targets named gramselecsim

# Build rule for target.
gramselecsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gramselecsim
.PHONY : gramselecsim

# fast build rule for target.
gramselecsim/fast:
	$(MAKE) $(MAKESILENT) -f GramsElecSim/CMakeFiles/gramselecsim.dir/build.make GramsElecSim/CMakeFiles/gramselecsim.dir/build
.PHONY : gramselecsim/fast

#=============================================================================
# Target rules for targets named AllFilesExample

# Build rule for target.
AllFilesExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AllFilesExample
.PHONY : AllFilesExample

# fast build rule for target.
AllFilesExample/fast:
	$(MAKE) $(MAKESILENT) -f scripts/CMakeFiles/AllFilesExample.dir/build.make scripts/CMakeFiles/AllFilesExample.dir/build
.PHONY : AllFilesExample/fast

#=============================================================================
# Target rules for targets named dEdxExample

# Build rule for target.
dEdxExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dEdxExample
.PHONY : dEdxExample

# fast build rule for target.
dEdxExample/fast:
	$(MAKE) $(MAKESILENT) -f scripts/CMakeFiles/dEdxExample.dir/build.make scripts/CMakeFiles/dEdxExample.dir/build
.PHONY : dEdxExample/fast

#=============================================================================
# Target rules for targets named gdmlsearch

# Build rule for target.
gdmlsearch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gdmlsearch
.PHONY : gdmlsearch

# fast build rule for target.
gdmlsearch/fast:
	$(MAKE) $(MAKESILENT) -f scripts/CMakeFiles/gdmlsearch.dir/build.make scripts/CMakeFiles/gdmlsearch.dir/build
.PHONY : gdmlsearch/fast

#=============================================================================
# Target rules for targets named healpix-maps

# Build rule for target.
healpix-maps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 healpix-maps
.PHONY : healpix-maps

# fast build rule for target.
healpix-maps/fast:
	$(MAKE) $(MAKESILENT) -f scripts/CMakeFiles/healpix-maps.dir/build.make scripts/CMakeFiles/healpix-maps.dir/build
.PHONY : healpix-maps/fast

#=============================================================================
# Target rules for targets named hepmc-convert

# Build rule for target.
hepmc-convert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hepmc-convert
.PHONY : hepmc-convert

# fast build rule for target.
hepmc-convert/fast:
	$(MAKE) $(MAKESILENT) -f scripts/CMakeFiles/hepmc-convert.dir/build.make scripts/CMakeFiles/hepmc-convert.dir/build
.PHONY : hepmc-convert/fast

#=============================================================================
# Target rules for targets named hepmc-grams-example

# Build rule for target.
hepmc-grams-example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hepmc-grams-example
.PHONY : hepmc-grams-example

# fast build rule for target.
hepmc-grams-example/fast:
	$(MAKE) $(MAKESILENT) -f scripts/CMakeFiles/hepmc-grams-example.dir/build.make scripts/CMakeFiles/hepmc-grams-example.dir/build
.PHONY : hepmc-grams-example/fast

#=============================================================================
# Target rules for targets named hepmc-ntuple

# Build rule for target.
hepmc-ntuple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hepmc-ntuple
.PHONY : hepmc-ntuple

# fast build rule for target.
hepmc-ntuple/fast:
	$(MAKE) $(MAKESILENT) -f scripts/CMakeFiles/hepmc-ntuple.dir/build.make scripts/CMakeFiles/hepmc-ntuple.dir/build
.PHONY : hepmc-ntuple/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AllFilesExample"
	@echo "... Dictionary"
	@echo "... GramsSimProjectUtilities"
	@echo "... dEdxExample"
	@echo "... gdmlsearch"
	@echo "... gramsdetsim"
	@echo "... gramselecsim"
	@echo "... gramsg4"
	@echo "... gramsreadoutsim"
	@echo "... gramssky"
	@echo "... healpix-maps"
	@echo "... hepmc-convert"
	@echo "... hepmc-grams-example"
	@echo "... hepmc-ntuple"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /nevis/milne/files/apellot/GRAMS/GramsSim-work/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

